### ISSUE TITLE
doesn't seem to work anymore

### ISSUE THREAD

**Issue by ptrcnull** [jrcichra/rocm-pytorch-gfx803#4]
`docker.io/jrcichra/rocm-pytorch-gfx803:latest` (`4906fc67fc5a` at the time) fails to even import torch:
```console
$ docker run --rm -it --privileged jrcichra/rocm-pytorch-gfx803 python3 -c 'import torch'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/lib/jenkins/pytorch/torch/__init__.py", line 201, in <module>
    from torch._C import _initExtension
ImportError: cannot import name '_initExtension'

```

**Comment by ptrcnull** [comment]
trying to build the image results in the following:
```
STEP 2/2: RUN git clone https://github.com/xuhuisheng/rocSPARSE && cd rocSPARSE && bash install.sh -di
Cloning into 'rocSPARSE'...
Creating project build directory in: ./build

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Ign:3 http://repo.radeon.com/rocm/apt/debian xenial InRelease
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]
Err:5 http://repo.radeon.com/rocm/apt/debian xenial Release
  404  Not Found [IP: 13.82.220.49 80]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3610 kB]
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2371 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [1466 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [30.8 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [20.5 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [64.0 kB]
Get:13 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [3190 kB]
Get:14 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [1426 kB]
Get:15 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1597 kB]
Get:16 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [23.8 kB]
Reading package lists...
E: The repository 'http://repo.radeon.com/rocm/apt/debian xenial Release' no longer has a Release file.
```
